import { render, screen } from '@testing-library/react'import ErrorBoundary from '../ErrorBoundary'// Component that throws an error on renderconst ProblemChild = () => {	throw new Error('Test crash')}describe('ErrorBoundary', () => {	it('catches error and displays fallback UI', () => {		render(			<ErrorBoundary>				<ProblemChild />			</ErrorBoundary>		)		expect(screen.getByText(/something went wrong/i)).toBeInTheDocument()		expect(screen.getByText(/test crash/i)).toBeInTheDocument()	})})